name: Build and Push Images
run-name: Builds each sub-drectory into a container
on:
  release:
    types: [published, prerelease]
jobs:
  build-containers:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: maven
      - name: Maven build
        run: cd java-spring && mvn clean package
      - name: Update environment
        run: |
          VVERSION=${{ github.event.release.tag_name }}
          VERSION=${VVERSION:1}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          mv java-spring/target/bakeoff-*.jar java-spring/target/bakeoff-${VERSION}.jar
          echo "JAR=target/bakeoff-${VERSION}.jar" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: danizen
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push bakeoff-django 
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:django"
          push: true
          tags: |
            danizen/bakeoff-django:latest
            danizen/bakeoff-django:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push bakeoff-fastapi-asyncpg
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:fastapi-asyncpg"
          push: true
          tags: |
            danizen/bakeoff-fastapi-asyncpg:latest
            danizen/bakeoff-fastapi-asyncpg:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push bakeoff-fastapi-orm-asyncpg
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:fastapi-orm-asyncpg"
          push: true
          tags: |
            danizen/bakeoff-fastapi-orm-asyncpg:latest
            danizen/bakeoff-fastapi-orm-asyncpg:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: investigate environment
        run: env
      - name: Build and push bakeoff-java-spring:${{ env.VERSION }}
        env:
          JAR: ${{ env.JAR }}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:java-spring"
          push: true
          tags: |
            danizen/bakeoff-java-spring:latest
            danizen/bakeoff-java-spring:${{ env.VERSION }}
      - name: Report Status
        run: echo "🍏 Built and Pushed danizen/bakeoff-django:${{ env.VERSION }}"
