name: Build and Push Images
run-name: Builds each sub-drectory into a container
on:
  release:
    types: [published, prerelease]
jobs:
  build-containers:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup VERSION variable
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
          echo "VERSION=${VERSION:1}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: danizen
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push bakeoff-django 
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:django"
          push: true
          tags: danizen/bakeoff-django:latest danizen/bakeoff-django:${{ env.VERSION }}
      - name: Report Status
        run: echo "🍏 Built and Pushed danizen/bakeoff-django:${{ env.VERSION }}"
