name: Build Containers
run-name: Builds each sub-drectory into a container
on: [push]
jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:django"
          push: false
          tags: danizen/bakeoff-django:latest
      - run: echo "🍏 This job's status is ${{ job.status }}."
