name: Build and Push Images
run-name: Builds each sub-drectory into a container
on:
  push:
    branches: ['main', 'master']
jobs:
  build-containers:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: maven
      - name: Maven build
        run: cd java-spring && mvn clean package